spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.drop-cascade: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  sql:
    init:
      mode: never
      data-locations: classpath:db/data.sql
