spring:
  application:
    name: core-bridge
  profiles:
    active: dev
  config:
    import:
      - "classpath:application-token.yml"
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  web:
    resources:
      static-locations: file:${upload.path}/PDF/

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

upload:
  path: ${UPLOAD_PATH}

password:
  reset:
    redirect:
      url: ${PWD_RESET_REDIRECT_URL}


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always